version: "3.9"
services:
  go-wallet-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      APP_PORT: 8080
      DB_HOST: database
      DB_NAME: wallet_db
      DB_USERNAME: user
      DB_PASSWORD: password
      SECRET_TOKEN_KEY: MY_SECRET_TOKEN_KEY
      ACCESS_TOKEN_DURATION: 200
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5