// Package api_gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api_gen

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for TransactionResponseDataType.
const (
	Deposit     TransactionResponseDataType = "deposit"
	TransferIn  TransactionResponseDataType = "transfer_in"
	TransferOut TransactionResponseDataType = "transfer_out"
	Withdraw    TransactionResponseDataType = "withdraw"
)

// DepositRequest defines model for DepositRequest.
type DepositRequest struct {
	Amount   float64 `json:"amount" validate:"required"`
	WalletId string  `json:"walletId" validate:"required"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email" validate:"required"`
	Password string `json:"password" validate:"required"`
}

// LoginResponseData defines model for LoginResponseData.
type LoginResponseData struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`
	UserId      string `json:"userId"`
}

// PageLimitResponseData defines model for PageLimitResponseData.
type PageLimitResponseData struct {
	// Limit The number of items per page.
	Limit int `json:"limit"`

	// Page The current page index (starting from 1).
	Page int `json:"page"`

	// TotalRecords The total number of records available.
	TotalRecords int `json:"totalRecords"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string `json:"displayName" validate:"required"`
	Email       string `json:"email" validate:"required"`
	Password    string `json:"password" validate:"required"`
}

// TransactionResponseData defines model for TransactionResponseData.
type TransactionResponseData struct {
	Amount       float64   `json:"amount"`
	CreatedAt    time.Time `json:"createdAt"`
	Description  *string   `json:"description,omitempty"`
	FromWalletId string    `json:"fromWalletId"`
	Id           string    `json:"id"`
	ToWalletId   string    `json:"toWalletId"`

	// Type Transaction type
	Type TransactionResponseDataType `json:"type"`
}

// TransactionResponseDataType Transaction type
type TransactionResponseDataType string

// TransferRequest defines model for TransferRequest.
type TransferRequest struct {
	Amount       float64 `json:"amount" validate:"required"`
	FromWalletId string  `json:"fromWalletId" validate:"required"`
	ToWalletId   string  `json:"toWalletId" validate:"required"`
}

// UpdateTransactionDescRequest defines model for UpdateTransactionDescRequest.
type UpdateTransactionDescRequest struct {
	Description *string `json:"description,omitempty"`
}

// WalletRequest defines model for WalletRequest.
type WalletRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name" validate:"required"`
}

// WalletResponseData defines model for WalletResponseData.
type WalletResponseData struct {
	Balance     float64   `json:"balance"`
	Description *string   `json:"description,omitempty"`
	Id          int       `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// WithdrawRequest defines model for WithdrawRequest.
type WithdrawRequest struct {
	Amount   float64 `json:"amount" validate:"required"`
	WalletId string  `json:"walletId" validate:"required"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorCode    string `json:"errorCode"`
	ErrorMessage string `json:"errorMessage"`
}

// ListUserWalletsResponse defines model for ListUserWalletsResponse.
type ListUserWalletsResponse struct {
	Data *[]WalletResponseData `json:"data,omitempty"`
}

// ListWalletTransactionsResponse defines model for ListWalletTransactionsResponse.
type ListWalletTransactionsResponse struct {
	Data       *[]TransactionResponseData `json:"data,omitempty"`
	Pagination *PageLimitResponseData     `json:"pagination,omitempty"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse = LoginResponseData

// WalletInfoResponse defines model for WalletInfoResponse.
type WalletInfoResponse struct {
	Data *WalletResponseData `json:"data,omitempty"`
}

// ListWalletTransactionsParams defines parameters for ListWalletTransactions.
type ListWalletTransactionsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// DepositMoneyJSONRequestBody defines body for DepositMoney for application/json ContentType.
type DepositMoneyJSONRequestBody = DepositRequest

// UpdateTransactionDescriptionJSONRequestBody defines body for UpdateTransactionDescription for application/json ContentType.
type UpdateTransactionDescriptionJSONRequestBody = UpdateTransactionDescRequest

// TransferBalanceJSONRequestBody defines body for TransferBalance for application/json ContentType.
type TransferBalanceJSONRequestBody = TransferRequest

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = WalletRequest

// UpdateWalletJSONRequestBody defines body for UpdateWallet for application/json ContentType.
type UpdateWalletJSONRequestBody = WalletRequest

// WithdrawMoneyJSONRequestBody defines body for WithdrawMoney for application/json ContentType.
type WithdrawMoneyJSONRequestBody = WithdrawRequest
