// Package api_gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api_gen

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// User login
	// (POST /public/login)
	LoginUser(c *gin.Context)
	// User registration
	// (POST /public/register)
	RegisterUser(c *gin.Context)
	// Deposit into a wallet
	// (POST /secure/deposit)
	DepositMoney(c *gin.Context)
	// Get transaction by ID
	// (GET /secure/transaction/{transactionId})
	GetTransactionDetails(c *gin.Context, transactionId string)
	// Update transaction description
	// (PATCH /secure/transaction/{transactionId})
	UpdateTransactionDescription(c *gin.Context, transactionId string)
	// Transfer between wallets
	// (POST /secure/transfer)
	TransferBalance(c *gin.Context)
	// Get all user wallets
	// (GET /secure/wallet)
	ListUserWallets(c *gin.Context)
	// Create a new wallet
	// (POST /secure/wallet)
	CreateWallet(c *gin.Context)
	// Delete a wallet by ID
	// (DELETE /secure/wallet/{walletId})
	DeleteWallet(c *gin.Context, walletId string)
	// Get wallet by ID
	// (GET /secure/wallet/{walletId})
	GetWalletById(c *gin.Context, walletId string)
	// Update wallet by ID
	// (PUT /secure/wallet/{walletId})
	UpdateWallet(c *gin.Context, walletId string)
	// List wallet transactions
	// (GET /secure/wallet/{walletId}/transactions)
	ListWalletTransactions(c *gin.Context, walletId string, params ListWalletTransactionsParams)
	// Withdraw from a wallet
	// (POST /secure/withdraw)
	WithdrawMoney(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginUser(c)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterUser(c)
}

// DepositMoney operation middleware
func (siw *ServerInterfaceWrapper) DepositMoney(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DepositMoney(c)
}

// GetTransactionDetails operation middleware
func (siw *ServerInterfaceWrapper) GetTransactionDetails(c *gin.Context) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", c.Param("transactionId"), &transactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter transactionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransactionDetails(c, transactionId)
}

// UpdateTransactionDescription operation middleware
func (siw *ServerInterfaceWrapper) UpdateTransactionDescription(c *gin.Context) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", c.Param("transactionId"), &transactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter transactionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTransactionDescription(c, transactionId)
}

// TransferBalance operation middleware
func (siw *ServerInterfaceWrapper) TransferBalance(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TransferBalance(c)
}

// ListUserWallets operation middleware
func (siw *ServerInterfaceWrapper) ListUserWallets(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListUserWallets(c)
}

// CreateWallet operation middleware
func (siw *ServerInterfaceWrapper) CreateWallet(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWallet(c)
}

// DeleteWallet operation middleware
func (siw *ServerInterfaceWrapper) DeleteWallet(c *gin.Context) {

	var err error

	// ------------- Path parameter "walletId" -------------
	var walletId string

	err = runtime.BindStyledParameterWithOptions("simple", "walletId", c.Param("walletId"), &walletId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter walletId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteWallet(c, walletId)
}

// GetWalletById operation middleware
func (siw *ServerInterfaceWrapper) GetWalletById(c *gin.Context) {

	var err error

	// ------------- Path parameter "walletId" -------------
	var walletId string

	err = runtime.BindStyledParameterWithOptions("simple", "walletId", c.Param("walletId"), &walletId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter walletId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWalletById(c, walletId)
}

// UpdateWallet operation middleware
func (siw *ServerInterfaceWrapper) UpdateWallet(c *gin.Context) {

	var err error

	// ------------- Path parameter "walletId" -------------
	var walletId string

	err = runtime.BindStyledParameterWithOptions("simple", "walletId", c.Param("walletId"), &walletId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter walletId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateWallet(c, walletId)
}

// ListWalletTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListWalletTransactions(c *gin.Context) {

	var err error

	// ------------- Path parameter "walletId" -------------
	var walletId string

	err = runtime.BindStyledParameterWithOptions("simple", "walletId", c.Param("walletId"), &walletId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter walletId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWalletTransactionsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListWalletTransactions(c, walletId, params)
}

// WithdrawMoney operation middleware
func (siw *ServerInterfaceWrapper) WithdrawMoney(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.WithdrawMoney(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/public/login", wrapper.LoginUser)
	router.POST(options.BaseURL+"/public/register", wrapper.RegisterUser)
	router.POST(options.BaseURL+"/secure/deposit", wrapper.DepositMoney)
	router.GET(options.BaseURL+"/secure/transaction/:transactionId", wrapper.GetTransactionDetails)
	router.PATCH(options.BaseURL+"/secure/transaction/:transactionId", wrapper.UpdateTransactionDescription)
	router.POST(options.BaseURL+"/secure/transfer", wrapper.TransferBalance)
	router.GET(options.BaseURL+"/secure/wallet", wrapper.ListUserWallets)
	router.POST(options.BaseURL+"/secure/wallet", wrapper.CreateWallet)
	router.DELETE(options.BaseURL+"/secure/wallet/:walletId", wrapper.DeleteWallet)
	router.GET(options.BaseURL+"/secure/wallet/:walletId", wrapper.GetWalletById)
	router.PUT(options.BaseURL+"/secure/wallet/:walletId", wrapper.UpdateWallet)
	router.GET(options.BaseURL+"/secure/wallet/:walletId/transactions", wrapper.ListWalletTransactions)
	router.POST(options.BaseURL+"/secure/withdraw", wrapper.WithdrawMoney)
}
